name: Run pre-commit
description: Run pre-commit
author: xsc27
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: true
    default: --all-files
  ssh-key:
    description: SSH key to access private repositories.
    required: false

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: pre-commit-${{ runner.os }}-
    - if: ${{ inputs.ssh-key }}
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ inputs.ssh-key }}
    - name: Install pre-commit
      run: pipx install pre-commit
      shell: bash
    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      shell: bash
