name: 'Run pre-commit'
description: 'Run pre-commit'
author: 'xsc27'
inputs:
  python-version:
    description: Version range or exact version of a Python version to use, using SemVer's version range syntax.
    default: '3.x'
    required: true
  skip-py-install:
    description: Skip installing Python.
    default: 'false'
    required: false
  extra_args:
    description: options to pass to pre-commit run
    required: true
    default: '--all-files'
  ssh-private-key:
    description: SSH key to access private pre-commit hooks.
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python
      if: ${{ ! fromJSON(inputs.skip-py-install) }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: pre-commit-${{ runner.os }}-
    - if: ${{ inputs.ssh-private-key }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Install pre-commit
      run: pip install pre-commit
      shell: bash
    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      shell: bash
